export const KOREAN_FIELDWORK_PEN_MEMO_COORDINATE_MAX = 10000;
export const KOREAN_FIELDWORK_PEN_MEMO_LINE_COUNT = 5;
export const KOREAN_FIELDWORK_PEN_MEMO_LINE_HEIGHT =
  KOREAN_FIELDWORK_PEN_MEMO_COORDINATE_MAX
  / KOREAN_FIELDWORK_PEN_MEMO_LINE_COUNT;
export const KOREAN_FIELDWORK_PEN_MEMO_GRID_STEP =
  KOREAN_FIELDWORK_PEN_MEMO_LINE_HEIGHT;
export const KOREAN_FIELDWORK_PEN_MEMO_PAGE_ASPECT_RATIO = 1;
